# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "Develop" ]
  pull_request:
    branches: [ "Develop" ]
    
permissions: 
  checks: write
  contents: write
  id-token: read
  discussions: write
  pull-requests: write
  repository-projects: read
  statuses: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --logger "trx;logfilename=TestResults.trx" --results-directory ./TestsReport --no-build --collect:"XPlat Code Coverage"
      
    - name: Post result
      uses: bibipkins/dotnet-test-reporter@v1.0.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        results-path: ./TestsReport
        comment-title: 'Unit Test Results'
        post-new-comment: true
      
    - name: Create tests report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Tests Report     # Name of the check run which will be created
        path: TestsReport/*    # Path to test results
        reporter: dotnet-trx     # Format of test results
        
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: TestsReport/**/coverage.cobertura.xml
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        output: both

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
